# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.SearchButton = QtWidgets.QPushButton(parent=Dialog)
        self.SearchButton.setGeometry(QtCore.QRect(270, 20, 113, 32))
        self.SearchButton.setObjectName("SearchButton")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 25, 150, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label.setObjectName("label")
        self.ShowLabel = QtWidgets.QLabel(parent=Dialog)
        self.ShowLabel.setGeometry(QtCore.QRect(30, 60, 341, 221))
        self.ShowLabel.setText("")
        self.ShowLabel.setObjectName("ShowLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MCBBS用户查询器"))
        self.SearchButton.setText(_translate("Dialog", "查询"))
        self.label.setText(_translate("Dialog", "请输入UID:"))
